/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: liquid.i

package liquid

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -L ./usr/include -lliquid -lm

extern void _wrap_Swig_free_liquid_aea15593472a9ba6(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_liquid_aea15593472a9ba6(swig_intgo arg1);
extern swig_intgo _wrap_LIQUIDIIRDESBUTTER_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESCHEBY1_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESCHEBY2_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESELLIP_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESBESSEL_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESLOWPASS_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESHIGHPASS_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESBANDPASS_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESBANDSTOP_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESSOS_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDIIRDESTF_liquid_aea15593472a9ba6(void);
extern uintptr_t _wrap_FirfiltRrrfCreate_liquid_aea15593472a9ba6(swig_voidp arg1, swig_intgo arg2);
extern void _wrap_FirfiltRrrfExecuteBlock_liquid_aea15593472a9ba6(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_voidp arg4);
extern uintptr_t _wrap_IirfiltCrcfCreatePrototype_liquid_aea15593472a9ba6(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4, float arg5, float arg6, float arg7, float arg8);
extern void _wrap_IirfiltCrcfExecuteBlock_liquid_aea15593472a9ba6(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_voidp arg4);
extern uintptr_t _wrap_MsresampCrcfCreate_liquid_aea15593472a9ba6(float arg1, float arg2);
extern void _wrap_MsresampCrcfExecute_liquid_aea15593472a9ba6(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_voidp arg4, swig_voidp arg5);
extern uintptr_t _wrap_FreqdemCreate_liquid_aea15593472a9ba6(float arg1);
extern void _wrap_FreqdemDemodulateBlock_liquid_aea15593472a9ba6(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3, swig_voidp arg4);
extern swig_intgo _wrap_LIQUIDNCO_liquid_aea15593472a9ba6(void);
extern swig_intgo _wrap_LIQUIDVCO_liquid_aea15593472a9ba6(void);
extern uintptr_t _wrap_NcoCrcfCreate_liquid_aea15593472a9ba6(swig_intgo arg1);
extern void _wrap_NcoCrcfSetFrequency_liquid_aea15593472a9ba6(uintptr_t arg1, float arg2);
extern void _wrap_NcoCrcfSetPhase_liquid_aea15593472a9ba6(uintptr_t arg1, float arg2);
extern void _wrap_NcoCrcfMixBlockUp_liquid_aea15593472a9ba6(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3, swig_intgo arg4);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_liquid_aea15593472a9ba6(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Liquid_iirdes_filtertype int
func _swig_getLIQUIDIIRDESBUTTER() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESBUTTER_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESBUTTER int = _swig_getLIQUIDIIRDESBUTTER()
func _swig_getLIQUIDIIRDESCHEBY1() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESCHEBY1_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESCHEBY1 int = _swig_getLIQUIDIIRDESCHEBY1()
func _swig_getLIQUIDIIRDESCHEBY2() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESCHEBY2_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESCHEBY2 int = _swig_getLIQUIDIIRDESCHEBY2()
func _swig_getLIQUIDIIRDESELLIP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESELLIP_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESELLIP int = _swig_getLIQUIDIIRDESELLIP()
func _swig_getLIQUIDIIRDESBESSEL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESBESSEL_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESBESSEL int = _swig_getLIQUIDIIRDESBESSEL()
type Liquid_iirdes_bandtype int
func _swig_getLIQUIDIIRDESLOWPASS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESLOWPASS_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESLOWPASS int = _swig_getLIQUIDIIRDESLOWPASS()
func _swig_getLIQUIDIIRDESHIGHPASS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESHIGHPASS_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESHIGHPASS int = _swig_getLIQUIDIIRDESHIGHPASS()
func _swig_getLIQUIDIIRDESBANDPASS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESBANDPASS_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESBANDPASS int = _swig_getLIQUIDIIRDESBANDPASS()
func _swig_getLIQUIDIIRDESBANDSTOP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESBANDSTOP_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESBANDSTOP int = _swig_getLIQUIDIIRDESBANDSTOP()
type Liquid_iirdes_format int
func _swig_getLIQUIDIIRDESSOS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESSOS_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESSOS int = _swig_getLIQUIDIIRDESSOS()
func _swig_getLIQUIDIIRDESTF() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDIIRDESTF_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDIIRDESTF int = _swig_getLIQUIDIIRDESTF()
func FirfiltRrrfCreate(arg1 []float32, arg2 uint) (_swig_ret Firfilt_rrrf_s) {
	var swig_r Firfilt_rrrf_s
	var _swig_i_0 *C.float
{
  _swig_i_0 = (*C.float)(&arg1[0])
}
	_swig_i_1 := arg2
	swig_r = (Firfilt_rrrf_s)(SwigcptrFirfilt_rrrf_s(C._wrap_FirfiltRrrfCreate_liquid_aea15593472a9ba6(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func FirfiltRrrfExecuteBlock(arg1 Firfilt_rrrf_s, arg2 []float32, arg3 uint, arg4 []float32) {
	_swig_i_0 := arg1.Swigcptr()
	var _swig_i_1 *C.float
{
  _swig_i_1 = (*C.float)(&arg2[0])
}
	_swig_i_2 := arg3
	var _swig_i_3 *C.float
{
  _swig_i_3 = (*C.float)(&arg4[0])
}
	C._wrap_FirfiltRrrfExecuteBlock_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func IirfiltCrcfCreatePrototype(arg1 Liquid_iirdes_filtertype, arg2 Liquid_iirdes_bandtype, arg3 Liquid_iirdes_format, arg4 uint, arg5 float32, arg6 float32, arg7 float32, arg8 float32) (_swig_ret Iirfilt_crcf_s) {
	var swig_r Iirfilt_crcf_s
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (Iirfilt_crcf_s)(SwigcptrIirfilt_crcf_s(C._wrap_IirfiltCrcfCreatePrototype_liquid_aea15593472a9ba6(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3), C.float(_swig_i_4), C.float(_swig_i_5), C.float(_swig_i_6), C.float(_swig_i_7))))
	return swig_r
}

func IirfiltCrcfExecuteBlock(arg1 Iirfilt_crcf_s, arg2 []complex64, arg3 uint, arg4 []complex64) {
	_swig_i_0 := arg1.Swigcptr()
	var _swig_i_1 *C.complexfloat
{
  _swig_i_1 = (*C.complexfloat)(&arg2[0])
}
	_swig_i_2 := arg3
	var _swig_i_3 *C.complexfloat
{
  _swig_i_3 = (*C.complexfloat)(&arg4[0])
}
	C._wrap_IirfiltCrcfExecuteBlock_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func MsresampCrcfCreate(arg1 float32, arg2 float32) (_swig_ret Msresamp_crcf_s) {
	var swig_r Msresamp_crcf_s
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Msresamp_crcf_s)(SwigcptrMsresamp_crcf_s(C._wrap_MsresampCrcfCreate_liquid_aea15593472a9ba6(C.float(_swig_i_0), C.float(_swig_i_1))))
	return swig_r
}

func MsresampCrcfExecute(arg1 Msresamp_crcf_s, arg2 []complex64, arg3 uint, arg4 []complex64, arg5 *uint) {
	_swig_i_0 := arg1.Swigcptr()
	var _swig_i_1 *C.complexfloat
{
  _swig_i_1 = (*C.complexfloat)(&arg2[0])
}
	_swig_i_2 := arg3
	var _swig_i_3 *C.complexfloat
{
  _swig_i_3 = (*C.complexfloat)(&arg4[0])
}
	_swig_i_4 := arg5
	C._wrap_MsresampCrcfExecute_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func FreqdemCreate(arg1 float32) (_swig_ret Freqdem_s) {
	var swig_r Freqdem_s
	_swig_i_0 := arg1
	swig_r = (Freqdem_s)(SwigcptrFreqdem_s(C._wrap_FreqdemCreate_liquid_aea15593472a9ba6(C.float(_swig_i_0))))
	return swig_r
}

func FreqdemDemodulateBlock(arg1 Freqdem_s, arg2 []complex64, arg3 uint, arg4 []float32) {
	_swig_i_0 := arg1.Swigcptr()
	var _swig_i_1 *C.complexfloat
{
  _swig_i_1 = (*C.complexfloat)(&arg2[0])
}
	_swig_i_2 := arg3
	var _swig_i_3 *C.float
{
  _swig_i_3 = (*C.float)(&arg4[0])
}
	C._wrap_FreqdemDemodulateBlock_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3))
}

type Liquid_ncotype int
func _swig_getLIQUIDNCO() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDNCO_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDNCO int = _swig_getLIQUIDNCO()
func _swig_getLIQUIDVCO() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_LIQUIDVCO_liquid_aea15593472a9ba6())
	return swig_r
}

var LIQUIDVCO int = _swig_getLIQUIDVCO()
func NcoCrcfCreate(arg1 Liquid_ncotype) (_swig_ret Nco_crcf_s) {
	var swig_r Nco_crcf_s
	_swig_i_0 := arg1
	swig_r = (Nco_crcf_s)(SwigcptrNco_crcf_s(C._wrap_NcoCrcfCreate_liquid_aea15593472a9ba6(C.swig_intgo(_swig_i_0))))
	return swig_r
}

func NcoCrcfSetFrequency(arg1 Nco_crcf_s, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_NcoCrcfSetFrequency_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func NcoCrcfSetPhase(arg1 Nco_crcf_s, arg2 float32) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_NcoCrcfSetPhase_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.float(_swig_i_1))
}

func NcoCrcfMixBlockUp(arg1 Nco_crcf_s, arg2 []complex64, arg3 []complex64, arg4 uint) {
	_swig_i_0 := arg1.Swigcptr()
	var _swig_i_1 *C.complexfloat
{
  _swig_i_1 = (*C.complexfloat)(&arg2[0])
}
	var _swig_i_2 *C.complexfloat
{
  _swig_i_2 = (*C.complexfloat)(&arg3[0])
}
	_swig_i_3 := arg4
	C._wrap_NcoCrcfMixBlockUp_liquid_aea15593472a9ba6(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_intgo(_swig_i_3))
}


type SwigcptrIirfilt_crcf_s uintptr
type Iirfilt_crcf_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrIirfilt_crcf_s) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrMsresamp_crcf_s uintptr
type Msresamp_crcf_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrMsresamp_crcf_s) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrNco_crcf_s uintptr
type Nco_crcf_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrNco_crcf_s) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrFreqdem_s uintptr
type Freqdem_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFreqdem_s) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrFirfilt_rrrf_s uintptr
type Firfilt_rrrf_s interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFirfilt_rrrf_s) Swigcptr() uintptr {
	return uintptr(p)
}

